spring:
  profiles: container
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  jackson:
    default-property-inclusion: NON_NULL
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '/*':
            allowedOriginPatterns: [ "*" ]
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
