spring:
  application:
    name: gateway-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://eureka-service-apb8.onrender.com/eureka
  instance:
    prefer-ip-address: true
    nonSecurePort: 6000
