server:
  port: 8080
spring:
  profiles: container
  main:
    web-application-type: reactive
  application:
    name: GATEWAY-SERVICE
  jackson:
    default-property-inclusion: NON_NULL
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '/*':
            allowedOriginPatterns: [ "http://localhost:3000","http://127.0.0.1:3000","http://localhost:4000", "http://localhost:4200", "http://localhost:8080"]
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
springdoc:
  pathsToMatch:
    - /cypher/**
    - /users/**
  api-docs:
    path: /api-docs
  swagger-ui:
    use-root-path: true
    disable-swagger-default-url: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: Cloud API
